Fix CI issue with OpenSSL-3.0 package which conflicts with setup-ruby
like so:
Run C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
[...]
loading package files...
checking for file conflicts...
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-openssl: /mingw64/bin/libcrypto-3-x64.dll exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/bin/libssl-3-x64.dll exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/etc/ssl/openssl.cnf exists in filesystem
Errors occurred, no packages were upgraded.